window_id: 1
choice_box_id: 0
font_id: 0
font_size: 25
info_window_width: 60
info_window_height: 30
info_window_x: 0
info_window_y: 450
selection_window_width: 42
selection_window_height: 30
selection_window_x: 600
selection_window_y: 450
party_x_placement: 100
party_y_placement: 350