window_id: 1
choice_box_id: 0
font_id: 0
font_size: 25

selection_window_width: 20
selection_window_height: 70
selection_window_x: 650
selection_window_y: 75
selection_window_spacing: 70

info_window_width: 20
info_window_height: 10
info_window_x: 650
info_window_y: 20

party_window_width: 50
party_window_height: 80
party_window_x: 120
party_window_y: 15