choice_box_window_id: 1
choice_box_selection_id: 0
choice_box_font_id: 0
choice_box_font_size: 25
choice_box_default_width: 10
choice_box_default_height: 15
choice_box_default_x: 800
choice_box_default_y: 400